package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller	// This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo
public class MainController {
	@Autowired // To get the bean called userRepository auto-generated by Spring to handle the data.
	private UserRepository userRepository;

	@GetMapping(path="/add") // URL's start with add to post the data ....
	// more to be done  to porost and get data from db
	
	public @ResponseBody String addNewUser (@RequestParam String name
			, @RequestParam String email) {
		// @ResponseBody(returned String is the response, not a view name)
		// @RequestParam(parameter from the GET or POST req)
	System.out.println("In add");
		User n = new User();
		n.setName(name);
		n.setEmail(email);
		userRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all") // url to get the user info stored in db.
	public @ResponseBody Iterable<User> getAllUsers() {
		// returns a JSON or XML (users)
		return userRepository.findAll();
	}
}
